version: '3'

services:
  backend:
    build:
      context: backend
      args:
        - HOSTUID=$HOSTUID
        - HOSTGID=$HOSTGID
        - HOSTUSER=$HOSTUSER
    command: phx.server
    volumes:
      - ../../:/chat
    ports:
      - 0.0.0.0:4000:4000

  postgres:
    build:
      context: postgres
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data
    env_file:
      - .envs/postgres.env
    ports:
      - 0.0.0.0:5432:5432
