version: '3'

services:
  backend:
    build:
      context: backend
      args:
        - HOSTUID=$HOSTUID
        - HOSTGID=$HOSTGID
        - HOSTUSER=$HOSTUSER
    command: phx.server
    volumes:
      - ../../:/chat
    ports:
      - 0.0.0.0:4000:4000
